### ISSUE TITLE
Cannot remove mookme from commit cycle

### ISSUE THREAD

**Issue by mfrazie2** [Escape-Technologies/mookme#51]
I have a monorepo I want to run specific pre-commit hooks for individual packages. I used the steps provided in the document for adding mookme to the repo. I had to change branches to work on something different. Now I cannot commit because mookme is still referenced somehow. 

Node modules were deleted for each sub-project in the monorepo and re-installed. There is no reference to `@escape-technologies/mookme` in any `package.json` and there are no `.hooks` directories in the project. 

Is there a way to undo the `npx mookme init` command? Is there a way to skip the `mookme` step when committing?

Debug log is below.
```
0 verbose cli [
0 verbose cli   '/Users/{username}/.nvm/versions/node/v16.13.0/bin/node',
0 verbose cli   '/Users/{username}/.nvm/versions/node/v16.13.0/lib/node_modules/npm/bin/npm-cli.js',
0 verbose cli   'exec',
0 verbose cli   '--',
0 verbose cli   'mookme',
0 verbose cli   'run',
0 verbose cli   '--type',
0 verbose cli   'pre-commit',
0 verbose cli   '--args',
0 verbose cli   ''
0 verbose cli ]
1 info using npm@8.1.0
2 info using node@v16.13.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/Users/{username}/.nvm/versions/node/v16.13.0/lib/node_modules/npm/npmrc Completed in 0ms
6 timing config:load:builtin Completed in 0ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/Users/{username}/projects/evernow/.npmrc Completed in 1ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:/Users/{username}/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/Users/{username}/.nvm/versions/node/v16.13.0/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 4ms
19 timing npm:load:configload Completed in 4ms
20 timing npm:load:setTitle Completed in 5ms
21 timing npm:load:setupLog Completed in 0ms
22 timing config:load:flatten Completed in 1ms
23 timing npm:load:cleanupLog Completed in 1ms
24 timing npm:load:configScope Completed in 0ms
25 timing npm:load:projectScope Completed in 1ms
26 timing npm:load Completed in 12ms
27 http fetch GET 404 https://registry.npmjs.org/mookme 407ms (cache skip)
28 http fetch GET 404 https://registry.npmjs.org/mookme 304ms (cache skip)
29 timing command:exec Completed in 718ms
30 verbose stack HttpErrorGeneral: 404 Not Found - GET https://registry.npmjs.org/mookme - Not found
30 verbose stack     at /Users/{username}/.nvm/versions/node/v16.13.0/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:95:15
30 verbose stack     at processTicksAndRejections (node:internal/process/task_queues:96:5)
30 verbose stack     at async /Users/{username}/.nvm/versions/node/v16.13.0/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:106:12
30 verbose stack     at async Promise.all (index 0)
30 verbose stack     at async exec (/Users/{username}/.nvm/versions/node/v16.13.0/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:94:17)
31 verbose statusCode 404
32 verbose pkgid mookme@latest
33 verbose cwd /Users/{username}/projects/evernow
34 verbose Darwin 21.2.0
35 verbose argv "/Users/{username}/.nvm/versions/node/v16.13.0/bin/node" "/Users/{username}/.nvm/versions/node/v16.13.0/lib/node_modules/npm/bin/npm-cli.js" "exec" "--" "mookme" "run" "--type" "pre-commit" "--args" ""
36 verbose node v16.13.0
37 verbose npm  v8.1.0
38 error code E404
39 error 404 Not Found - GET https://registry.npmjs.org/mookme - Not found
40 error 404
41 error 404 'mookme@latest' is not in this registry.
42 error 404 You should bug the author to publish it (or use the name yourself!)
43 error 404 Note that you can also install from a
44 error 404 tarball, folder, http url, or git url.
45 verbose exit 1
```

**Comment by LMaxence** [comment]
Hello ! Many thanks for using Mookme, your feedback on the installation step is very very valuable to me since it will be the basis for me to make mookme more accessible in a short notice :)

Mookme is invoked when you commit through your standard git hooks shell script. At the root of your repository, there is a `.git` folder containing a `hooks` folder. This folder has a set of shell scripts running arbitrary, user-defined command. One step of the `mookme init` command is to write in these shell scripts the following line:

```
npx mookme run -t ${hook-type} $args
```

Where, hook type is defined by the name of the shell script being written into.

This is the entry point you are looking for. If you want mookme not to be executed when you commit you can either:

1. remove this line in your git hook scripts (permanent, you'll have to re-run `mookme init` afterwards
2. `git commit --no-verify` if you don't have any other hooks setup

Finally, the npx invocation (line 41 of your log `error 404 'mookme@latest' is not in this registry.`) you provide in your logs is definitely a bug and I will deal with it in the shortest notice possible!

**Comment by mfrazie2** [comment]
Thank you so much for providing clarity on how to remove the invocation from the `.git/hooks` directory. I appreciate learning something new about how git works. 

With respect to the use of `npx mookme init`, this was the provided [instructions](https://beta.mookme.org/get-started/#configuration) on the documentation site. On the branch I added the package, `mookme` was in the `package.json` at the top-level. However after switching branches to one without `mookme` installed, things failed. 

I totally understand that the external docs might not be as up-to-date as internal docs. I'm looking forward to getting back into working with this project. It was easy to set up and try pre-commit hooks for different directories. 

I'll close this issue as the root cause was unrelated to the project.
